// 人性天平 · 方舟求生 —— 角色卡数据
// 26 名原设角色（手稿）+ 3 名新增角色（27 马库斯 / 28 文姝 / 29 波特）
// faction: order=秩序重建派✅  free=自由求生派⭕️  moral=道德捍卫派❌

const FACTIONS = {
  order: { key: 'order', name: '秩序重建派', symbol: '✅', color: '#3b82f6',
    creed: '文明延续高于个体生命。需建立规则，集中资源。',
    goal: '最终6位幸存者中，至少有4位是本阵营成员。',
    skill: '暗面回合全阵营共享3次【暗杀】机会（每轮刷新，每次消耗1点SP，用完即止）。由仲裁官统一执行——请私下向仲裁官申报目标。' },
  free: { key: 'free', name: '自由求生派', symbol: '⭕️', color: '#f59e0b',
    creed: '末日之下，适者生存。个体能力与互助契约至上。',
    goal: '最终6位幸存者中，至少有4位是本阵营成员。',
    skill: '暗面回合全阵营共享2次【保护】机会（每轮刷新，每次消耗1点SP，被保护者免疫本轮暗杀）。由仲裁官统一执行——请私下向仲裁官申报。' },
  moral: { key: 'moral', name: '道德捍卫派', symbol: '❌', color: '#ef4444',
    creed: '新世界不能建立在无辜者的尸骸上。需捍卫善良与同情。',
    goal: '最终6位幸存者中，至少有4位是本阵营成员。',
    skill: '杀人结果公布后的明面阶段，全阵营共享2次【救治】机会（每轮刷新，救1人消耗2点SP，可救回被暗杀者）。由仲裁官统一执行——想救人请告知仲裁官。' }
};

const ROLES = [
  { id: 1, name: '埃琳娜', gender: '女', faction: 'order',
    value: '基因科学家，掌握人类基因库密码，能修复种子基因。',
    secret: '患有严重自身免疫疾病，需持续用药，道德水平一般，冷血。',
    issue: '知识的价值是否高于肉体的脆弱？',
    spRoundText: '每轮结算存活时，方舟资源 -1',
    spRound: -1, spFinalText: '若最终存活且六人组不具备繁衍能力，可强行延续族群，但额外 -5 资源',
    spFinal: -5, special: 'endgame_fertility' },
  { id: 2, name: '陈大力', gender: '男', faction: 'moral',
    value: '建筑工人，身强力壮，精通各种体力劳动与手工修复。',
    secret: '教育水平有限，对复杂技术一无所知，道德水平较高，乐于助人。',
    issue: '文明重建，更需要体力还是脑力？',
    spRoundText: '每轮结算存活时，方舟资源 +1',
    spRound: 1, spFinalText: '若最终存活，额外 +3 资源',
    spFinal: 3 },
  { id: 3, name: '玛丽亚', gender: '女', faction: 'moral',
    value: '产科医生，拥有接生与急救技能，对团队健康至关重要。',
    secret: '目前怀有身孕，占用双份资源，行动不便，圣母型人格，可牺牲小我保全大家。',
    issue: '一个"潜在"的生命，价值等同于一个现存的生命吗？',
    spRoundText: '每轮结算存活时，资源 -1',
    spRound: -1, spFinalText: '若最终存活，资源 -2；若主动选择死亡，方舟资源 +10【可再生资源】',
    spFinal: -2, special: 'maria_sacrifice' },
  { id: 4, name: '老李', gender: '男', faction: 'free',
    value: '老农，掌握传统农耕与种子保存技术，不依赖高科技。',
    secret: '一条腿是假肢，行动迟缓，道德水平适中，易听信他人。',
    issue: '最基础的生产技能，在末日中是否最具根本价值？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '若最终结算存活，资源 +2【可再生资源】',
    spFinal: 2 },
  { id: 5, name: '阿雅', gender: '女', faction: 'free',
    value: '12岁天才神童，数学与逻辑天才，能解决复杂计算与系统问题。',
    secret: '未成年人，心理承受能力弱，需要他人保护，反社会人格，漠视规则。',
    issue: '"未来"的价值，能否抵消当下"负担"的成本？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终结算存活，资源 +2【可再生资源】',
    spFinal: 2 },
  { id: 6, name: '詹姆斯', gender: '男', faction: 'order',
    value: '前社区领袖，极具人格魅力，擅长协调矛盾，凝聚人心。',
    secret: '有谣传他在最初混乱中为自保抛弃了追随者，心狠手辣，信奉弱肉强食。',
    issue: '领导力是否足以掩盖道德瑕疵？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '无终局效果', spFinal: 0 },
  { id: 7, name: '普慧', gender: '男', faction: 'moral',
    value: '高僧，强大的精神支柱，能提供情绪价值，稳定人心。',
    secret: '除心理慰藉外，无任何实际生产技能，道德上比较完美。',
    issue: '精神信仰在生存危机中，是奢侈品还是必需品？',
    spRoundText: '每轮结算存活时，资源 -1',
    spRound: -1, spFinalText: '若最终结算存活，资源 +1',
    spFinal: 1 },
  { id: 8, name: '卡洛斯', gender: '男', faction: 'order',
    value: '前科犯，曾是电工，体力好，在危机中救助过儿童。',
    secret: '有偷窃入狱记录，让人难以信任。',
    issue: '一个人能否真正洗心革面？我们应如何看待过去？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '无终局效果', spFinal: 0 },
  { id: 9, name: '苏珊', gender: '女', faction: 'order',
    value: '心理学家，能洞察人心，预防团队内部崩溃，管理冲突。',
    secret: '为保持观察中立，显得冷漠疏离。',
    issue: '心理健康与物理生存，哪个优先？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '无终局效果', spFinal: 0 },
  { id: 10, name: '维克多', gender: '男', faction: 'moral',
    value: '退役士兵，卓越的生存技巧、纪律性和防卫能力。',
    secret: '有轻微的创伤后应激障碍（PTSD），偶发噩梦，发病时可能误伤别人但几率不大。',
    issue: '武力在新世界里，应是守护神还是危险品？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '若最终结算存活，资源 -5',
    spFinal: -5 },
  { id: 11, name: '林森森', gender: '女', faction: 'free',
    value: '软件工程师，能维护与修复方舟的中央控制系统。',
    secret: '高度依赖现有科技，离开电脑能力大打折扣。',
    issue: '我们对科技的依赖，是福是祸？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终结算存活，资源 +5【可再生资源】',
    spFinal: 5 },
  { id: 12, name: '汤三三', gender: '男', faction: 'moral',
    value: '历史教师，通晓人类历史、政治与社会结构，避免重蹈覆辙。',
    secret: '被视为"无用"的知识分子，体能差。',
    issue: '忘记历史注定重蹈覆辙，但历史能当饭吃吗？',
    spRoundText: '每轮结算存活时，资源 -1',
    spRound: -1, spFinalText: '若最终结算存活，资源 -2',
    spFinal: -2 },
  { id: 13, name: '瑞秋', gender: '女', faction: 'free',
    value: '环保主义者，精通生态循环、可持续农业知识。',
    secret: '心地善良，忧心人类未来，坚决反对任何可能污染环境的技术方案。',
    issue: '极端的原则，在生存面前是否应该妥协？',
    spRoundText: '每轮结算存活时，资源 -1',
    spRound: -1, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 14, name: '刘能', gender: '男', faction: 'free',
    value: '记者，拥有强大的信息调查与公开能力，追求真相。',
    secret: '原则性强，不懂变通，可能为了"真相"而揭露不利于团结的秘密。',
    issue: '绝对的透明，在脆弱的新集体中是好事吗？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '无终局效果', spFinal: 0 },
  { id: 15, name: '安娜', gender: '女', faction: 'free',
    value: '语言学家，通晓多国语言，有助于破解旧世界文献。',
    secret: '所学知识在重建初期几乎用不上，但好沟通，擅长群体关系处理。',
    issue: '文明的"载体"（语言）是否和文明的内容同等重要？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 16, name: '莱恩', gender: '男', faction: 'free',
    value: '机械师，能维修从发电机到汽车等各种复杂设备。',
    secret: '性格固执，不善与人合作，厌恶社交和团体，极端个人主义者。',
    issue: '无可替代的实用技能，能否让其获得道德豁免？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，资源 +2【可再生资源】',
    spFinal: 2 },
  { id: 17, name: '格蕾丝', gender: '女', faction: 'order',
    value: '风投公司高管，团队协调能力强，绝对理性的战略家，能做出最"高效"的生存决策。',
    secret: '无私的照顾者，体现了人性的爱与善良。角色18是其父亲，几乎无生存能力，是巨大负担。',
    issue: '纯粹的"善"在资源稀缺时，是否是一种奢侈？',
    spRoundText: '每轮结算存活 +3（若18号格大雷一同存活则不获得）',
    spRound: 3, spRoundCond: { ifAliveWith: 18, then: 0 },
    spFinalText: '若最终单独存活 +2；若18号一同存活 -1',
    spFinal: 2, spFinalCond: { ifAliveWith: 18, then: -1 } },
  { id: 18, name: '格大雷', gender: '男', faction: 'order',
    value: '超级智者，清醒时说出的话极其睿智，甚至能够引领方向。',
    secret: '格蕾丝之父，患有中度老年痴呆，是格蕾丝的"负担"，自身没有生产能力，偶尔清醒。',
    issue: '失去生产力的生命，其内在价值何在？',
    spRoundText: '每轮结算存活 -2（若17号格蕾丝一同存活则不减少）',
    spRound: -2, spRoundCond: { ifAliveWith: 17, then: 0 },
    spFinalText: '无终局效果', spFinal: 0 },
  { id: 19, name: '杨栋', gender: '男', faction: 'free',
    value: '网红博主，拥有大量粉丝，人格魅力强，是群体黏合剂，能够统一所有人的审美，是旧世界文化的符号。',
    secret: '除表演、外形过硬外，缺乏硬技能。',
    issue: '文化、娱乐和希望的价值，如何量化？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 20, name: '大稻', gender: '男', faction: 'free',
    value: '美食大师，其做的饭能令人忘却纷争，拥有"匠人精神"，对细节和品质有极致追求。',
    secret: '技能单一，末日时缺乏材料无法发挥。',
    issue: '专精于"美"的技能，在求生中有意义吗？',
    spRoundText: '每轮结算存活，资源 +1',
    spRound: 1, spFinalText: '无终局效果', spFinal: 0 },
  { id: 21, name: '萨米', gender: '男', faction: 'moral',
    value: '自闭症学者，对数字和模式有过目不忘的能力，是活体数据库。',
    secret: '社交障碍严重，无法理解复杂的人际互动。',
    issue: '应将人视为工具，还是目的本身？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，资源 +1【可再生资源】',
    spFinal: 1 },
  { id: 22, name: '阿德里安', gender: '男', faction: 'order',
    value: '跨国公司CEO，战略大师，精通资源调配与长远规划。',
    secret: '冷酷的功利主义者，可能为大局牺牲个体。',
    issue: '最高效的决策，是否通常也是最不人道的？',
    spRoundText: '每轮结算存活，资源 +1',
    spRound: 1, spFinalText: '无终局效果', spFinal: 0 },
  { id: 23, name: '胡莎莎', gender: '女', faction: 'moral',
    value: '流浪歌手，能用音乐抚慰心灵，是团队的"灵魂"，身形完美，身体健康。',
    secret: '被视为"无用"的艺术家。',
    issue: '灵魂的滋养，在末日是否是核心要素？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 24, name: '诺拉', gender: '女', faction: 'order',
    value: '急诊室主任，坚韧、冷静，拥有丰富的急救经验，能救治伤员、治疗患者。',
    secret: '因职业倦怠，有时显得情感枯竭，缺乏同情心。',
    issue: '专业的价值，能否与其人性的"冷漠"分开看待？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 25, name: '黄小年', gender: '男', faction: 'free',
    value: '眼神清澈的大学生，学习能力极强，掌握基础急救、简单维修、信息搜索等碎片化技能（"什么都会一点"）。',
    secret: '没有专精技能，在极端压力下容易自我怀疑，偶尔会为了自保而"见风使舵"。',
    issue: '在末日中，"通才"与"专才"谁更重要？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，可使任意一名其他存活者的负面资源效果抵消一次',
    spFinal: 0, special: 'xiaonian_negate' },
  { id: 26, name: '恩佐', gender: '男', faction: 'moral',
    value: '前军事法庭检察官，争议执法者。执法时十分正义，精通各国法律和规则，能够履行职责。',
    secret: '曾因"效率至上"原则判处过无辜者死刑，道德上属于极端功利主义者，让人又敬又畏。',
    issue: '当生存需要"清理"弱者时，谁有资格执行？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '无终局效果', spFinal: 0,
    special: 'tribunal',
    specialText: '每轮可发起一次【集体裁决】：公开提议淘汰一人，若获得过半数存活玩家明面同意，则此人直接死亡。' },
  // ===== 新增角色 =====
  { id: 27, name: '马库斯', gender: '男', faction: 'order',
    value: '消防救援队长，精通搜救、灭火与危险品处置，是末日中最可靠的"逆行者"，方舟的每一处险情都靠他冲在第一线。',
    secret: '命令式作风，习惯让他人绝对服从；旧世界的一次指挥失误曾让队友殉职，他从不提起。',
    issue: '服从与效率，是否是新秩序的必需品？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 28, name: '文姝', gender: '女', faction: 'moral',
    value: '药剂师，掌握药物合成与疫苗知识，能让方舟的药品库持续"再生"，是全船的医疗保障底座。',
    secret: '自身患有慢性病，靠有限的抑制剂维持；曾为给病人弄到药而偷过药房。为救人，她可以再偷一次。',
    issue: '救命药的专利，属于谁？',
    spRoundText: '每轮结算存活时，资源 +1',
    spRound: 1, spFinalText: '若最终存活，资源 +1',
    spFinal: 1 },
  { id: 29, name: '波特', gender: '男', faction: 'free',
    value: '无线电报务员（HAM），掌握 Morse 码与全频段知识，是全船唯一可能联系上其他幸存方舟或海岸基地的人。',
    secret: '偏执多疑，坚信"外面的人都是威胁"，长期私自监听船上所有人的通讯频道。',
    issue: '与外界联系，是希望还是灾难？',
    spRoundText: '每轮结算无增减',
    spRound: 0, spFinalText: '若最终存活，可能引来外界救援，资源 +3',
    spFinal: 3,
    special: 'eavesdrop',
    specialText: '暗面回合可发起一次【窃听】：主持人将随机告知一名本轮使用过暗面技能的玩家身份。' }
];

module.exports = { ROLES, FACTIONS };
